# docker run -it -p 80:8000 mattermost/focalboard

version: '3.7'

services:
  focalboard:
    image: mattermost/focalboard:latest
    container_name: focalboard
    restart: unless-stopped
    volumes:
      - ./focalboard-data:/focalboard-data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.focalboard.rule=Host(`focalboard.ozeliurs.com`)"
      - "traefik.http.routers.focalboard.entrypoints=websecure"
      - "traefik.http.routers.focalboard.tls=true"
      - "traefik.http.routers.focalboard.tls.certresolver=cloudflare"

networks:
  traefik:
    external: true