version: '3.7'

services:
  dokku:
    image: dokku/dokku:0.30.1
    container_name: dokku
    restart: unless-stopped
    volumes:
      - dokku:/var/lib/dokku
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOKKU_HOSTNAME=dokku.ozeliurs.com
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku
      - DOKKU_LIB_HOST_ROOT=/var/lib/dokku/var/lib/dokku
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dokku.rule=Host(`dokku.ozeliurs.com`)"
      - "traefik.http.routers.dokku.entrypoints=websecure"
      - "traefik.http.routers.dokku.tls=true"
      - "traefik.http.routers.dokku.tls.certresolver=cloudflare"
      - "traefik.http.services.dokku.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  dokku: