version: '3.5'
services:

  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    volumes:
      - ./container-config:/etc/headscale
      - ./container-data/data:/var/lib/headscale
    ports:
      - 8080:8080
    entrypoint: headscale serve
    restart: unless-stopped