version: '3.9'
services:
  minio:
    command: 'server --console-address ":9001"'
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      - MINIO_VOLUMES=/mnt/data
    env_file:
      - .env
    volumes:
      - './data:/mnt/data'
    ports:
      - '9000:9000'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.minio.rule=Host(`minio.ozeliurs.com`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"

networks:
  traefik:
    external: true