version: '3.9'
services:
  minio:
    command: 'server --console-address ":9090"'
    image: minio/minio:latest
    container_name: minio_local
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - '/etc/default/minio:/etc/config.env'
      - './data:/mnt/data'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.ozeliurs.com`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.rule=Host(`minio.ozeliurs.com`) && PathPrefix(`/minio`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9090"

networks:
  traefik:
    external: true