server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://log.ozeliurs.com/loki/api/v1/push

basic_auth:
  # The username to use for basic auth
  username: "log"

  # The file containing the password for basic auth
  password_file: /etc/promtail/basicauth

# local machine logs
# scrape_configs:
# - job_name: local
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: varlogs
#       __path__: /var/log/*log
  
# docker logs  
scrape_configs:
  - job_name: docker 
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log