version: '3.7'

services:
  vault:
    image: vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    command: server -config=/vault/config/vault.hcl -non-interactive -log-level=debug
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
      - ./vault:/vault
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.ozeliurs.com`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.tls.certresolver=cloudflare"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"

networks:
  traefik:
    external: true