version: '3.7'

services:
  kiwix:
    image: kiwix/kiwix-serve:latest
    container_name: kiwix
    restart: unless-stopped
    command: /zim/*.zim
    volumes:
      - ./zim:/zim
    environment:
     - LIBRARY_PATH=/library.xml
     - ZIM_PATH=/zim
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiwix.rule=Host(`wikipedia.ozeliurs.com`)"
      - "traefik.http.routers.kiwix.entrypoints=websecure"
      - "traefik.http.routers.kiwix.tls=true"
      - "traefik.http.routers.kiwix.tls.certresolver=cloudflare"
      - "traefik.http.services.kiwix.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
