version: '3.7'

services:
  kiwix:
    image: kiwix/kiwix-serve:latest
    container_name: kiwix
    restart: unless-stopped
    ports:
      - 5000:8080
    volumes:
      - ./library.xml:/library.xml
      - ./zim:/zim
    environment:
     - LIBRARY_PATH=/library.xml
     - ZIM_PATH=/zim