version: "3"
services:

  wiki-db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - wiki-db-data:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    networks:
      - traefik

  wiki:
    image: ghcr.io/requarks/wiki:2
    restart: unless-stopped
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: wiki
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki.rule=Host(`wiki.ozeliurs.com`)
      - traefik.http.routers.wiki.entrypoints=websecure
      - traefik.http.routers.wiki.tls=true
      - traefik.http.routers.wiki.tls.certresolver=cloudflare
      - traefik.http.services.wiki.loadbalancer.server.port=3000
    networks:
      - traefik

volumes:
  wiki-db-data:

networks:
  traefik:
    external: true