version: '3'
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - paperless

  web:
    image: jonaswinkler/paperless-ng:latest
    container_name: paperless-ng
    restart: unless-stopped
    depends_on:
      - broker
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./consume:/usr/src/paperless/consume
      - ./export:/usr/src/paperless/export
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    networks:
      - traefik
      - paperless
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paper.ozeliurs.com`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.routers.paperless.tls.certresolver=cloudflare"
      - "traefik.http.services.plask.loadbalancer.server.port=8000"

networks:
  traefik:
    external: true
  paperless:
    external: false