version: '3'
services:
  redis_paperless:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ng
    restart: unless-stopped
    depends_on:
      - redis_paperless
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./consume:/usr/src/paperless/consume
      - ./export:/usr/src/paperless/export
    environment:
      - PAPERLESS_URL=https://paper.ozeliurs.com
      - PAPERLESS_REDIS=redis://redis_paperless:6379
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paper.ozeliurs.com`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.routers.paperless.tls.certresolver=cloudflare"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.http.routers.paperless.middlewares=authelia@docker"

networks:
  traefik:
    external: true