version: '3'

services:
  web:
    image: ozeliurs/plask:latest
    restart: always
    volumes:
      - ./persistent:/app/persistent
    env_file:
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plask.rule=Host(`plask.ozeliurs.com`)"
      - "traefik.http.routers.plask.entrypoints=websecure"
      - "traefik.http.routers.plask.tls=true"
      - "traefik.http.routers.plask.tls.certresolver=cloudflare"
      - "traefik.http.services.plask.loadbalancer.server.port=5000"
    

networks:
  traefik:
    external: true