version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    restart: always
    volumes:
      - ./.memos/:/var/opt/memos
    ports:
      - 8096:5230
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memos.rule=Host(`notes.ozeliurs.com`)"
      - "traefik.http.routers.memos.entrypoints=websecure"
      - "traefik.http.routers.memos.tls=true"
      - "traefik.http.routers.memos.tls.certresolver=cloudflare"
      - "traefik.http.services.memos.loadbalancer.server.port=5230"