version: '3'

services:
  web:
    image: sagemathinc/cocalc:latest
    container_name: cocalc
    restart: unless-stopped
    volumes:
      - ./data:/projects
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`cocalc.ozeliurs.com`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.services.gitea.loadbalancer.server.port=80"
      - "traefik.http.routers.gitea.tls.certresolver=cloudflare"
    
networks:
  traefik:
    external: true