name: 👨‍💼 User Story
description: Add a user story
title: "US: As a <role>, I want <goal/desire> so that <benefit>."
assignees:
  - ozeliurs
  - Apoorva64
  - BedinoTom
  - neoteristis
labels: [ "user-story" ]
projects: [ "BytEats" ]

body:
  - type: markdown
    attributes:
      value: ⚠️ Firstly fill out the title of your User Story ⚠️
  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      description: The difficulty of the User Story.
      options:
        - XS 💤
        - S 👍
        - M ⚠️
        - L ‼️
        - XL 🫄
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: The priority of the User Story.
      options:
        - 1 (Low)
        - 10 (Medium)
        - 100 (High)
        - 1000 (Critical)
        - 10000 (Blocker)
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: The acceptance criteria are the conditions that the story must meet to be considered complete and finished.
      placeholder: 1. If I do <A>, <B> should happen.
    validations:
      required: true

