version: '3.7'

services:
  neo4j-api:
    image: ghcr.io/the-contextualizer/neo4j-backend/neo4j-backend:latest
    container_name: neo4j-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NEO4J_HOST=neo4j
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neo4j-api.rule=Host(`neo4j-api.tc.ozeliurs.com`)"
      - "traefik.http.routers.neo4j-api.entrypoints=websecure"
      - "traefik.http.routers.neo4j-api.tls=true"
      - "traefik.http.routers.neo4j-api.tls.certresolver=cloudflare"

      - "com.centurylinklabs.watchtower.enable=true"

  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    networks:
      - traefik
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8443:8443"
    labels:
      - "traefik.enable=false"
    
networks:
  traefik:
    external: true
