version: "3"

services:

  sonarqube:
    image: git.ozeliurs.com/ozeliurs/sonarqube:10.1.2
    restart: unless-stopped
    depends_on:
      - db_sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db_sonarqube:5432/sonar
      SONAR_JDBC_USERNAME: ${DB_USER}
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.ozeliurs.com`)"
      - "traefik.http.routers.sonarqube.entrypoints=websecure"
      - "traefik.http.routers.sonarqube.tls=true"
      - "traefik.http.routers.sonarqube.tls.certresolver=cloudflare"

  db_sonarqube:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - traefik

  sonar_buddy:
    image: ozeliurs/sonar-buddy:latest
    restart: unless-stopped
    depends_on:
      - sonarqube
    env_file:
      - .env.example
    environment:
      - SONAR_HOST="sonarqube.ozeliurs.com"
      - BASE_URL="https://sonarqube.ozeliurs.com/reset_password"
    volumes:
      - ./users.csv:/app/users.csv
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarbuddy.rule=Host(`sonarqube.ozeliurs.com`) && PathPrefix(`/reset_password`)"
      - "traefik.http.routers.sonarbuddy.entrypoints=websecure"
      - "traefik.http.routers.sonarbuddy.tls=true"
      - "traefik.http.routers.sonarbuddy.tls.certresolver=cloudflare"
      - "traefik.http.routers.sonarbuddy.service=sonarbuddy"
      - "traefik.http.services.sonarbuddy.loadbalancer.server.port=8080"
      #- "traefik.http.routers.middlewares=sonarbuddy-stripprefix"
      #- "traefik.http.middlewares.sonarbuddy-stripprefix.stripprefix.prefixes=/reset_password"

networks:
  traefik:
    external: true