version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: EU766m5js@GQ
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "8098:9000"
    restart: always
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: EU766m5js@GQ
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: always

volumes:
  sonarqube_data:
    driver_opts:
        type: none
        device: sonarqube/data
        o: bind
  sonarqube_extensions:
    driver_opts:
        type: none
        device: sonarqube/extensions
        o: bind
  sonarqube_logs:
    driver_opts:
        type: none
        device: sonarqube/logs
        o: bind
  postgresql:
    driver_opts:
        type: none
        device: postgresql
        o: bind
  postgresql_data:
    driver_opts:
        type: none
        device: postgresql/data
        o: bind