version: "3"

services:

  timetagger:
    image: ghcr.io/almarklein/timetagger:latest
    restart: unless-stopped
    volumes:
      - ./timetagger:/root/_timetagger
    networks:
      - traefik
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.timetagger.rule=Host(`timetagger.ozeliurs.com`)"
      - "traefik.http.routers.timetagger.entrypoints=websecure"
      - "traefik.http.routers.timetagger.tls=true"
      - "traefik.http.routers.timetagger.tls.certresolver=cloudflare"
      - "traefik.http.services.timetagger.loadbalancer.server.port=80"

networks:
  traefik:
    external: true