###############################################################
#                   Authelia configuration                    #
###############################################################

# jwt_secret: a_very_important_secret ## Set by AUTHELIA_JWT_SECRET_FILE in docker-compose
default_redirection_url: https://ozeliurs.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: two_factor
  # rules:
    # TODO: Add rules to bypass 2FA for specific domains
    # - domain: public.example.com
    #   policy: bypass

session:
  # secret: unsecure_session_secret ## Set by AUTHELIA_SESSION_SECRET_FILE in docker-compose
  domain: ozeliurs.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: 2PDHwoCAYuUYaFrYA99Ypv8X5NhtpnTQssni3aThEwRuTYasvYeeBVbqwgHHDPWY7Z6hP8zsW46tRLPWhenXX2QBZ3br3qjqikWHD33yZUKrvF7nXaP4LkCeCcDWotiS
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
  # smtp:
    # username: test
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: password
    # host: mail.example.com
    # port: 25
    # sender: admin@example.com