version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.18.3
    restart: unless-stopped
    volumes:
      - ./weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'weaviate.ozeliurs.com'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weaviate.rule=Host(`weaviate.ozeliurs.com`)"
      - "traefik.http.routers.weaviate.entrypoints=websecure"
      - "traefik.http.routers.weaviate.tls=true"
      - "traefik.http.services.weaviate.loadbalancer.server.port=8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
      
networks:
  traefik:
    external: true