global:
  checkNewVersion: true
  sendAnonymousUsage: false

# (Optional) Log information
# ---
log:
 level: WARNING  # DEBUG, INFO, WARNING, ERROR(Default), CRITICAL
#   format: common  # common, json, logfmt
#   filePath: /var/log/traefik/traefik.log

# (Optional) Accesslog
# ---
accesslog:
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/access.log

# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: true  # false for production or dont expose port for production
  insecure: true  # false for production

metrics:
  prometheus:
    entryPoint: traefik
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80

    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "ozeliurs.com"
            sans: "*.ozeliurs.com"

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@ozeliurs.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  cloudflare:
    acme:
      email: admin@ozeliurs.com
      storage: /letsencrypt/cf.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
  

# (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

providers:
  docker:
    exposedByDefault: false
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
