version: '3'

services:
  neo4j:
    image: neo4j:4.4-community
    container_name: neo4j
    restart: unless-stopped
    expose:
      - 7474
      - 7687
    volumes:
      - ./volumes/neo4j-data:/data/dbms
      - ./volumes/neo4j-logs:/logs
      - ./volumes/neo4j-import:/var/lib/neo4j/import
      - ./volumes/neo4j-plugins:/plugins
      - ./volumes/neo4j-certificates:/certificates
      - ./volumes/neo4j-backup:/var/lib/neo4j/backup
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - dbms.connector.bolt.listen_address=:7687
      - dbms.connector.bolt.advertised_address=:7687
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neo4j.rule=Host(`neo4j.arm.ozeliurs.com`)"
      - "traefik.http.routers.neo4j.entrypoints=websecure"
      - "traefik.http.routers.neo4j.tls=true"
      - "traefik.http.routers.neo4j.tls.certresolver=cloudflare"
      - "traefik.http.services.neo4j.loadbalancer.server.port=7687"

networks:
  traefik:
    external: true