services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_dbms_default__advertised__address=neo4j.ozeliurs.com
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/var/lib/neo4j/certificates/
      - NEO4J_dbms_ssl_policy_bolt_private__key=key.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=certificate.crt
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_dbms_connector_bolt_tls__level=REQUIRED
      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/var/lib/neo4j/certificates/
      - NEO4J_dbms_ssl_policy_https_private__key=key.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=certificate.crt
      - NEO4J_dbms_ssl_policy_https_client__auth=NONE
    env_file:
      - .env
    volumes:
      - ../traefik/letsencrypt/certificates/neo4j.ozeliurs.com:/var/lib/neo4j/certificates/
    networks:
      - traefik
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8443:8443"

networks:
  traefik:
    external: true