version: '3'
services:

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://umami:umami@db_umami:5432/umami
      DATABASE_TYPE: postgresql
    env_file:
      - .env
    depends_on:
      - db_umami
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`umami.ozeiurs.com`)"
      - "traefik.http.routers.umami.entrypoints=websecure"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"
      - "traefik.http.routers.umami.tls.certresolver=cloudflare"

  db_umami:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

volumes:
  umami-db-data:

networks:
  traefik:
    external: true