version: '3'
services:
  web:
    image: nginx
    container_name: blog-ozeliurs-com
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog-ozeliurs-com.rule=Host(`blog.ozeliurs.com`)"
      - "traefik.http.routers.blog-ozeliurs-com.entrypoints=websecure"
      - "traefik.http.routers.blog-ozeliurs-com.tls=true"
      - "traefik.http.routers.blog-ozeliurs-com.tls.certresolver=cloudflare"

networks:
  traefik:
    external: true
