version: '3.0'

services:
  pihole:
    container_name: pihole
    build: build/.
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
  traefik:
    external: true