version: '3.0'

services:
  pihole:
    container_name: pihole
    # build: build/.
    image: cbcrowe/pihole-unbound:latest
    restart: unless-stopped
    ports:
      - "173.249.4.153:53:53/tcp"
      - "173.249.4.153:53:53/udp"
    environment:
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    networks:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.ozeliurs.com`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
  traefik:
    external: true