version: '3'
services:
  web:
    image: nginx
    container_name: cf-ozeliurs-com
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro
    ports:
     - "8088:80"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cf-ozeliurs-com.rule=Host(`cf.ozeliurs.com`)"
      - "traefik.http.routers.cf-ozeliurs-com.entrypoints=websecure"
      - "traefik.http.routers.cf-ozeliurs-com.tls=true"
      - "traefik.http.routers.cf-ozeliurs-com.tls.certresolver=cloudflare"

networks:
  traefik:
    external: true