version: '3'
services:
  web:
    image: nginx
    container_name: cf-ozeliurs-com
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro
    ports:
     - "8088:80"
    healthcheck:
      test: [ "CMD", "service", "nginx" ,"status", "||", "exit", "1" ]
      timeout: 45s
      interval: 30s
      retries: 5