version: "3"

services:
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki:/etc/loki
      - ./data:/tmp/loki
    user: "0"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`log.ozeliurs.com`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.middlewares.loki.users=logs:$$2y$$05$$LRwz0OsJs2FNITnjSLXUFOj5o7/dl3kj.gBvuMaukJt7ETGyOmIPm"
      - "traefik.http.routers.loki.tls.certresolver=cloudflare"

  grafana:
    image: grafana/grafana:latest
    user: "0"
    volumes:
    - ./grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.ozeliurs.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"

networks:
  traefik:
    external: true